<a href="https://colab.research.google.com/github/jarinkhan/Credit-Data/blob/main/Credit_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split


data = pd.read_csv('CreditData.csv')


X = data.drop('Approved', axis=1)
y = data['Approved']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
data = pd.read_csv('CreditData.csv')

X = data.drop('Approved', axis=1)
y = data['Approved']

#pre
le = LabelEncoder()
for col in X.columns:
    if X[col].dtype == 'object':
        X[col] = le.fit_transform(X[col])


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

lr_model = LogisticRegression(max_iter=1000)  # Increase max_iter to 1000
lr_model.fit(X_train, y_train)

#Logistic Regression model on test data
lr_predictions = lr_model.predict(X_test)

# Calculate evaluation metrics with 'Yes' as the positive class
lr_confusion_matrix = confusion_matrix(y_test, lr_predictions)
lr_accuracy = accuracy_score(y_test, lr_predictions)
lr_precision = precision_score(y_test, lr_predictions, pos_label='Yes')
lr_recall = recall_score(y_test, lr_predictions, pos_label='Yes')

print("Logistic Regression Results:")
print("Confusion Matrix:")
print(lr_confusion_matrix)
print("Accuracy:", lr_accuracy)
print("Precision:", lr_precision)
print("Recall:", lr_recall)

Logistic Regression Results:
Confusion Matrix:
[[ 27  32]
 [ 14 127]]
Accuracy: 0.77
Precision: 0.7987421383647799
Recall: 0.900709219858156

In [ ]:
test

,Status,Duration,history,Purpose,amount,Savings,employment,Installment,sex,guarantors,...,Property,Age,OtherInstallment,Housing,ExistingCredits,Job,liable,Telephone,foreign,Approved
178,A14,12,A32,A43,1963,A61,A74,4,A93,A101,...,A123,31,A143,A151,2,A174,2,A192,A201,Yes
559,A12,18,A34,A42,1928,A61,A72,2,A93,A101,...,A121,31,A143,A152,2,A172,1,A191,A201,No
540,A12,12,A32,A43,1534,A61,A72,1,A94,A101,...,A121,23,A143,A151,1,A173,1,A191,A201,No
959,A12,24,A32,A42,3069,A62,A75,4,A93,A101,...,A124,30,A143,A153,1,A173,1,A191,A201,Yes
552,A11,48,A32,A43,6999,A61,A74,1,A94,A103,...,A121,34,A143,A152,2,A173,1,A192,A201,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,A14,9,A34,A42,2406,A61,A71,2,A93,A101,...,A123,31,A143,A152,1,A174,1,A191,A201,Yes
141,A12,36,A32,A43,4795,A61,A72,4,A92,A101,...,A124,30,A143,A152,1,A174,1,A192,A201,Yes
584,A14,12,A32,A40,2133,A65,A75,4,A92,A101,...,A124,52,A143,A153,1,A174,1,A192,A201,Yes
666,A12,30,A31,A42,3496,A64,A73,4,A93,A101,...,A123,34,A142,A152,1,A173,2,A192,A201,Yes
638,A14,12,A32,A43,1493,A61,A72,4,A92,A101,...,A123,34,A143,A152,1,A173,2,A191,A201,Yes

In [ ]:
train

,Status,Duration,history,Purpose,amount,Savings,employment,Installment,sex,guarantors,...,Property,Age,OtherInstallment,Housing,ExistingCredits,Job,liable,Telephone,foreign,Approved
155,A11,12,A32,A42,1282,A61,A73,2,A92,A101,...,A123,20,A143,A151,1,A173,1,A191,A201,No
268,A11,14,A32,A40,8978,A61,A75,1,A91,A101,...,A122,45,A143,A152,1,A174,1,A192,A202,No
100,A14,24,A32,A40,1469,A62,A75,4,A94,A101,...,A121,41,A143,A151,1,A172,1,A191,A201,Yes
842,A14,18,A32,A45,1943,A61,A72,4,A92,A101,...,A121,23,A143,A152,1,A173,1,A191,A201,No
487,A14,24,A32,A40,3757,A61,A75,4,A92,A102,...,A124,62,A143,A153,1,A173,1,A192,A201,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,A11,24,A32,A40,1285,A65,A74,4,A92,A101,...,A124,32,A143,A151,1,A173,1,A191,A201,No
240,A11,24,A32,A40,915,A65,A75,4,A92,A101,...,A123,29,A141,A152,1,A173,1,A191,A201,No
943,A14,4,A34,A40,1455,A61,A74,2,A93,A101,...,A121,42,A143,A152,3,A172,2,A191,A201,Yes
45,A14,11,A34,A40,1393,A61,A72,4,A92,A101,...,A123,35,A143,A152,2,A174,1,A191,A201,Yes
390,A14,18,A32,A40,1820,A61,A73,2,A94,A101,...,A122,30,A143,A152,1,A174,1,A192,A201,Yes

In [ ]:
data['Approved'].value_counts()

Yes    700
No     300
Name: Approved, dtype: int64

In [ ]:
y_train

29      No
535     No
695    Yes
557     No
836    Yes
      ...
106     No
270    Yes
860    Yes
435     No
102    Yes
Name: Approved, Length: 800, dtype: object